# Generated by Django 3.2.8 on 2021-10-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
